In [1]:
import pandas as pd
import numpy as np

# 1 Creating Dataframe From Array
## 1.1 Option_1

In [ ]:
#Creating an Array
data = np.array([[1,4], [2,5], [3,6]])

In [3]:
#Craeting a dataframe...
data = pd.DataFrame(data, index = ["row1", "row2", "row3"],
                    columns = ["column1", "column2"])

In [4]:
data

      column1  column2
row1        1        4
row2        2        5
row3        3        6

## 1.2 Option2

In [5]:
import pandas as pd 
import numpy as np

In [6]:
data = np.array([[1,2],[3,4]])

In [7]:
dataset = pd.DataFrame(data, index = ("row1", "row2"),
                       columns = ("column1", "column2"))

In [8]:
dataset

      column1  column2
row1        1        2
row2        3        4

# 2. Creating a Dataframe from a dictionary...

In [9]:
states = ["Kolkata", "Delhi", "Pune"]
population = [120000, 46772, 736454]

In [10]:
dictionary = {"States":states, "Populationns":population}

In [11]:
data = pd.DataFrame(dictionary)
data

    States  Populationns
0  Kolkata        120000
1    Delhi         46772
2     Pune        736454

# Creating a data frame from a  csv file

In [12]:
data = pd.read_csv("student-scores.csv")

In [13]:
data.head(10)

,id,first_name,last_name,email,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score
0,1,Paul,Casey,paul.casey.1@gslingacademy.com,male,False,3,False,27,Lawyer,73,81,93,97,63,80,87
1,2,Danielle,Sandoval,danielle.sandoval.2@gslingacademy.com,female,False,2,False,47,Doctor,90,86,96,100,90,88,90
2,3,Tina,Andrews,tina.andrews.3@gslingacademy.com,female,False,9,True,13,Government Officer,81,97,95,96,65,77,94
3,4,Tara,Clark,tara.clark.4@gslingacademy.com,female,False,5,False,3,Artist,71,74,88,80,89,63,86
4,5,Anthony,Campos,anthony.campos.5@gslingacademy.com,male,False,5,False,10,Unknown,84,77,65,65,80,74,76
5,6,Kelly,Wade,kelly.wade.6@gslingacademy.com,female,False,2,False,26,Unknown,93,100,67,78,72,80,84
6,7,Anthony,Smith,anthony.smith.7@gslingacademy.com,male,False,3,True,23,Software Engineer,99,96,97,73,88,76,64
7,8,George,Short,george.short.8@gslingacademy.com,male,True,2,True,34,Software Engineer,95,95,82,63,84,70,85
8,9,Stanley,Gutierrez,stanley.gutierrez.9@gslingacademy.com,male,False,6,False,25,Unknown,94,68,94,85,81,74,72
9,10,Audrey,Simpson,audrey.simpson.10@gslingacademy.com,female,False,3,True,18,Teacher,98,69,88,71,67,71,73

In [14]:
data.tail(11)

,id,first_name,last_name,email,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score
1989,1990,Samuel,Baker,samuel.baker.1990@gslingacademy.com,male,False,2,False,17,Stock Investor,77,86,97,85,77,88,93
1990,1991,Anthony,Moore,anthony.moore.1991@gslingacademy.com,male,False,0,False,17,Software Engineer,98,63,64,82,64,96,79
1991,1992,Charlotte,Rowe,charlotte.rowe.1992@gslingacademy.com,female,False,4,False,27,Lawyer,88,96,79,70,95,90,99
1992,1993,John,Peterson,john.peterson.1993@gslingacademy.com,male,False,2,True,12,Banker,79,83,76,99,100,84,71
1993,1994,Shawn,Ochoa,shawn.ochoa.1994@gslingacademy.com,male,False,3,False,46,Doctor,92,92,91,95,88,94,93
1994,1995,Steven,Lewis,steven.lewis.1995@gslingacademy.com,male,False,1,False,19,Accountant,76,62,90,82,93,71,61
1995,1996,Alan,Reynolds,alan.reynolds.1996@gslingacademy.com,male,False,2,False,30,Construction Engineer,83,77,84,73,75,84,82
1996,1997,Thomas,Gilbert,thomas.gilbert.1997@gslingacademy.com,male,False,2,False,20,Software Engineer,89,65,73,80,87,67,73
1997,1998,Madison,Cross,madison.cross.1998@gslingacademy.com,female,False,5,False,14,Software Engineer,97,85,63,93,68,94,78
1998,1999,Brittany,Compton,brittany.compton.1999@gslingacademy.com,female,True,10,True,5,Business Owner,51,96,72,89,95,88,75
1999,2000,Natalie,Smith,natalie.smith.2000@gslingacademy.com,female,False,5,False,27,Accountant,82,99,91,69,83,93,100

In [15]:
data.shape

(2000, 17)

In [16]:
# Displaying the number of rows
pd.set_option("display.max_rows", 1000)
data

,id,first_name,last_name,email,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score
0,1,Paul,Casey,paul.casey.1@gslingacademy.com,male,False,3,False,27,Lawyer,73,81,93,97,63,80,87
1,2,Danielle,Sandoval,danielle.sandoval.2@gslingacademy.com,female,False,2,False,47,Doctor,90,86,96,100,90,88,90
2,3,Tina,Andrews,tina.andrews.3@gslingacademy.com,female,False,9,True,13,Government Officer,81,97,95,96,65,77,94
3,4,Tara,Clark,tara.clark.4@gslingacademy.com,female,False,5,False,3,Artist,71,74,88,80,89,63,86
4,5,Anthony,Campos,anthony.campos.5@gslingacademy.com,male,False,5,False,10,Unknown,84,77,65,65,80,74,76
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,Alan,Reynolds,alan.reynolds.1996@gslingacademy.com,male,False,2,False,30,Construction Engineer,83,77,84,73,75,84,82
1996,1997,Thomas,Gilbert,thomas.gilbert.1997@gslingacademy.com,male,False,2,False,20,Software Engineer,89,65,73,80,87,67,73
1997,1998,Madison,Cross,madison.cross.1998@gslingacademy.com,female,False,5,False,14,Software Engineer,97,85,63,93,68,94,78
1998,1999,Brittany,Compton,brittany.compton.1999@gslingacademy.com,female,True,10,True,5,Business Owner,51,96,72,89,95,88,75
1999,2000,Natalie,Smith,natalie.smith.2000@gslingacademy.com,female,False,5,False,27,Accountant,82,99,91,69,83,93,100

# 1. Attributes

In [17]:
# Getting access to the shape attribute of the dataframe   
data.shape

(2000, 17)

In [18]:
# Getting access to the index attribute of the dataframe
data.index

RangeIndex(start=0, stop=2000, step=1)

In [19]:
# Get access to the columns attribute of the dataframe
data.columns

Index(['id', 'first_name', 'last_name', 'email', 'gender', 'part_time_job',
       'absence_days', 'extracurricular_activities', 'weekly_self_study_hours',
       'career_aspiration', 'math_score', 'history_score', 'physics_score',
       'chemistry_score', 'biology_score', 'english_score', 'geography_score'],
      dtype='object')

In [20]:
# Data types of the columns in the dataframe
data.dtypes

id                             int64
first_name                    object
last_name                     object
email                         object
gender                        object
part_time_job                   bool
absence_days                   int64
extracurricular_activities      bool
weekly_self_study_hours        int64
career_aspiration             object
math_score                     int64
history_score                  int64
physics_score                  int64
chemistry_score                int64
biology_score                  int64
english_score                  int64
geography_score                int64
dtype: object

# 2. Methods

In [21]:
# Showing the first 5 columns of the dataframe
data.columns[:5]

Index(['id', 'first_name', 'last_name', 'email', 'gender'], dtype='object')

In [22]:
# Showing the info of the dataframe
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id                          2000 non-null   int64
 1   first_name                  2000 non-null   object
 2   last_name                   2000 non-null   object
 3   email                       2000 non-null   object
 4   gender                      2000 non-null   object
 5   part_time_job               2000 non-null   bool
 6   absence_days                2000 non-null   int64
 7   extracurricular_activities  2000 non-null   bool
 8   weekly_self_study_hours     2000 non-null   int64
 9   career_aspiration           2000 non-null   object
 10  math_score                  2000 non-null   int64
 11  history_score               2000 non-null   int64
 12  physics_score               2000 non-null   int64
 13  chemistry_score             2000 non-null   int64
 14  biology_score               2000 non-null   int64
 15  english_score               2000 non-null   int64
 16  geography_score             2000 non-null   int64
dtypes: bool(2), int64(10), object(5)
memory usage: 238.4+ KB

In [23]:
# Describing basic statistical details of the dataframe
data.describe()

,id,absence_days,weekly_self_study_hours,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.00000,2000.000000,2000.000000
mean,1000.500000,3.665500,17.755500,83.452000,80.332000,81.336500,79.995000,79.58150,81.277500,80.888000
std,577.494589,2.629271,12.129604,13.224906,12.736046,12.539453,12.777895,13.72219,12.027087,11.637705
min,1.000000,0.000000,0.000000,40.000000,50.000000,50.000000,50.000000,30.00000,50.000000,60.000000
25%,500.750000,2.000000,5.000000,77.000000,69.750000,71.000000,69.000000,69.00000,72.000000,71.000000
50%,1000.500000,3.000000,18.000000,87.000000,82.000000,83.000000,81.000000,81.00000,83.000000,81.000000
75%,1500.250000,5.000000,28.000000,93.000000,91.000000,92.000000,91.000000,91.00000,91.000000,91.000000
max,2000.000000,10.000000,50.000000,100.000000,100.000000,100.000000,100.000000,100.00000,99.000000,100.000000

# 3. Functions

In [24]:
# obtain the length of the dataframe
len(data)

2000

In [25]:
# Obtaining the highest index value of the dataframe
max(data)

'weekly_self_study_hours'

In [26]:
# Obtaining the highest index value of the dataframe
data.index.max()

1999

In [27]:
# Obtaining the lowest index value of the dataframe
data.index.min()

0

In [28]:
# Obtain the data types
type(data)

pandas.core.frame.DataFrame

# 1 Selecting one column

## 1.1 Syntax_1

In [29]:
data["email"]

0                paul.casey.1@gslingacademy.com
1         danielle.sandoval.2@gslingacademy.com
2              tina.andrews.3@gslingacademy.com
3                tara.clark.4@gslingacademy.com
4            anthony.campos.5@gslingacademy.com
                         ...
1995       alan.reynolds.1996@gslingacademy.com
1996      thomas.gilbert.1997@gslingacademy.com
1997       madison.cross.1998@gslingacademy.com
1998    brittany.compton.1999@gslingacademy.com
1999       natalie.smith.2000@gslingacademy.com
Name: email, Length: 2000, dtype: object

In [34]:
# Select two or more columns of the dataframe
data[["email", "gender", "math_score"]]

                                        email  gender  math_score
0              paul.casey.1@gslingacademy.com    male          73
1       danielle.sandoval.2@gslingacademy.com  female          90
2            tina.andrews.3@gslingacademy.com  female          81
3              tara.clark.4@gslingacademy.com  female          71
4          anthony.campos.5@gslingacademy.com    male          84
...                                       ...     ...         ...
1995     alan.reynolds.1996@gslingacademy.com    male          83
1996    thomas.gilbert.1997@gslingacademy.com    male          89
1997     madison.cross.1998@gslingacademy.com  female          97
1998  brittany.compton.1999@gslingacademy.com  female          51
1999     natalie.smith.2000@gslingacademy.com  female          82

[2000 rows x 3 columns]

# 1. Adding a new column...

## 1.1/ Adding a new column with a scalar value...

In [35]:
data["language_score"] = 70
data

,id,first_name,last_name,email,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,language_score
0,1,Paul,Casey,paul.casey.1@gslingacademy.com,male,False,3,False,27,Lawyer,73,81,93,97,63,80,87,70
1,2,Danielle,Sandoval,danielle.sandoval.2@gslingacademy.com,female,False,2,False,47,Doctor,90,86,96,100,90,88,90,70
2,3,Tina,Andrews,tina.andrews.3@gslingacademy.com,female,False,9,True,13,Government Officer,81,97,95,96,65,77,94,70
3,4,Tara,Clark,tara.clark.4@gslingacademy.com,female,False,5,False,3,Artist,71,74,88,80,89,63,86,70
4,5,Anthony,Campos,anthony.campos.5@gslingacademy.com,male,False,5,False,10,Unknown,84,77,65,65,80,74,76,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,Alan,Reynolds,alan.reynolds.1996@gslingacademy.com,male,False,2,False,30,Construction Engineer,83,77,84,73,75,84,82,70
1996,1997,Thomas,Gilbert,thomas.gilbert.1997@gslingacademy.com,male,False,2,False,20,Software Engineer,89,65,73,80,87,67,73,70
1997,1998,Madison,Cross,madison.cross.1998@gslingacademy.com,female,False,5,False,14,Software Engineer,97,85,63,93,68,94,78,70
1998,1999,Brittany,Compton,brittany.compton.1999@gslingacademy.com,female,True,10,True,5,Business Owner,51,96,72,89,95,88,75,70
1999,2000,Natalie,Smith,natalie.smith.2000@gslingacademy.com,female,False,5,False,27,Accountant,82,99,91,69,83,93,100,70

## 1.2 Adding a new column with an array

In [38]:
# creating a random int between 40 and 100
data["language_score"] = np.random.randint(40, 80, size = len(data))
data

,id,first_name,last_name,email,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,language_score
0,1,Paul,Casey,paul.casey.1@gslingacademy.com,male,False,3,False,27,Lawyer,73,81,93,97,63,80,87,75
1,2,Danielle,Sandoval,danielle.sandoval.2@gslingacademy.com,female,False,2,False,47,Doctor,90,86,96,100,90,88,90,73
2,3,Tina,Andrews,tina.andrews.3@gslingacademy.com,female,False,9,True,13,Government Officer,81,97,95,96,65,77,94,65
3,4,Tara,Clark,tara.clark.4@gslingacademy.com,female,False,5,False,3,Artist,71,74,88,80,89,63,86,61
4,5,Anthony,Campos,anthony.campos.5@gslingacademy.com,male,False,5,False,10,Unknown,84,77,65,65,80,74,76,79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,Alan,Reynolds,alan.reynolds.1996@gslingacademy.com,male,False,2,False,30,Construction Engineer,83,77,84,73,75,84,82,62
1996,1997,Thomas,Gilbert,thomas.gilbert.1997@gslingacademy.com,male,False,2,False,20,Software Engineer,89,65,73,80,87,67,73,60
1997,1998,Madison,Cross,madison.cross.1998@gslingacademy.com,female,False,5,False,14,Software Engineer,97,85,63,93,68,94,78,72
1998,1999,Brittany,Compton,brittany.compton.1999@gslingacademy.com,female,True,10,True,5,Business Owner,51,96,72,89,95,88,75,74
1999,2000,Natalie,Smith,natalie.smith.2000@gslingacademy.com,female,False,5,False,27,Accountant,82,99,91,69,83,93,100,42

## 1.2 Insert()
### insert  a column at a specific position or index...

In [ ]:
data.insert(1, "test_score", np.random.randint(40, 80, size = len(data)))

In [40]:
data

,id,test_score,first_name,last_name,email,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,language_score
0,1,48,Paul,Casey,paul.casey.1@gslingacademy.com,male,False,3,False,27,Lawyer,73,81,93,97,63,80,87,75
1,2,65,Danielle,Sandoval,danielle.sandoval.2@gslingacademy.com,female,False,2,False,47,Doctor,90,86,96,100,90,88,90,73
2,3,61,Tina,Andrews,tina.andrews.3@gslingacademy.com,female,False,9,True,13,Government Officer,81,97,95,96,65,77,94,65
3,4,66,Tara,Clark,tara.clark.4@gslingacademy.com,female,False,5,False,3,Artist,71,74,88,80,89,63,86,61
4,5,57,Anthony,Campos,anthony.campos.5@gslingacademy.com,male,False,5,False,10,Unknown,84,77,65,65,80,74,76,79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,64,Alan,Reynolds,alan.reynolds.1996@gslingacademy.com,male,False,2,False,30,Construction Engineer,83,77,84,73,75,84,82,62
1996,1997,67,Thomas,Gilbert,thomas.gilbert.1997@gslingacademy.com,male,False,2,False,20,Software Engineer,89,65,73,80,87,67,73,60
1997,1998,75,Madison,Cross,madison.cross.1998@gslingacademy.com,female,False,5,False,14,Software Engineer,97,85,63,93,68,94,78,72
1998,1999,53,Brittany,Compton,brittany.compton.1999@gslingacademy.com,female,True,10,True,5,Business Owner,51,96,72,89,95,88,75,74
1999,2000,44,Natalie,Smith,natalie.smith.2000@gslingacademy.com,female,False,5,False,27,Accountant,82,99,91,69,83,93,100,42

# 1. Math_Operations...

### 1.1/ Operations in column...

In [41]:
data["math_score"].sum()

np.int64(166904)

In [42]:
data["math_score"].count()

np.int64(2000)

In [43]:
data["math_score"].mean()

np.float64(83.452)

In [45]:
data["math_score"].max()

100

In [46]:
data["math_score"].min()

40

### 1.2 Operation in Rows...

In [47]:
data["physics_score"] + data["math_score"] + data["language_score"]

0       241
1       259
2       241
3       220
4       228
       ...
1995    229
1996    222
1997    232
1998    197
1999    215
Length: 2000, dtype: int64

In [52]:
x = (data["physics_score"] + data["math_score"] + data["language_score"]).mean()

In [55]:
x.round(1)

np.float64(224.2)